version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /package/id
    schedule:
      interval: daily
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /package/migrate
    schedule:
      interval: daily
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /package/om
    schedule:
      interval: daily
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /package/schema
    schedule:
      interval: daily
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /package/server
    schedule:
      interval: daily
    labels:
      - dependencies
